
sidebar:
  - title: Fuzzy Palm Tree
    url: /
  - title: Om prosjektet
    url: /om
  - title: Ingen begrensninger
    url: https://github.com/Roaldstveit/fuzzy-palm-tree/tree/main#ingen-begrensninger
  - title: Totalt frislepp
    url: /Roaldstveit/fuzzy-palm-tree/tree/main#totalt-frislepp
